

GET http://localhost:3000/api/tarifas/662e26cb38a7ec7e6eddcbff


###

GET http://localhost:3000/api/tarifas/type/fibra

###

GET http://localhost:3000/api/tarifas/name/Plan Oro

###
GET http://localhost:3000/api/tarifas/data/Móvil 120GB + ilimitadas

###
GET http://localhost:3000/api/tarifas/type/movil/data/Móvil 120GB + ilimitadas

###
POST http://localhost:3000/api/tarifas
Content-Type: application/json

{
    "type": "Móvil",
    "name": "Plan Prueba",
    "data":"Móvil 100GB + ilimitadas",
    "price": 10.90
   
}

###
PUT http://localhost:3000/api/tarifas/662e26cb38a7ec7e6eddcbfe
Content-Type: application/json

{
    "name": "Plan oro",
    "price": 8.95
}

###
DELETE http://localhost:3000/api/tarifas/662fe1ebe23f507ed7248fed